"""

Implements the end-to-end Retrieval-Augmented Generation (RAG) pipeline.

The pipeline retrieves relevant video context, constructs a prompt,
and generates an answer using the language model.
"""

from config import config
from Code.Retriever.hybrid_retriever import hybrid_retrieve
from Code.Retriever.prompt_builder import build_prompt
from Code.model.llm_model import generate_answer
from Code.utils.logger import get_logger

logger = get_logger(__name__)


def chat(question):
    """
    Generate an answer for a user query using the RAG pipeline.

    Parameters
    ----------
    question : str
        User's question.

    Returns
    -------
    str
        Answer generated by the language model.
    """

    logger.info("Started hybrid_retrieve")

    retrieved_docs = hybrid_retrieve(query=question, top_k=config.TOP_K)
    logger.info("completed hybrid_retrieve")

    logger.info("calling prompt")
    prompt = build_prompt(question, retrieved_docs)
    logger.info("Started generate_answer")
    answer = generate_answer(prompt)

    return answer
